In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, confusion_matrix, accuracy_score
import numpy as np

file_path = '/content/winequality-red.csv'
wine_data = pd.read_csv(file_path)

X = wine_data.drop('quality', axis=1)
y = wine_data['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



rf_model = RandomForestRegressor(random_state=42, n_estimators=100)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
rf_mse = mean_squared_error(y_test, rf_predictions)
print(f"Random Forest Mean Squared Error: {rf_mse}")

rf_predictions_rounded = np.round(rf_predictions)

rf_cm = confusion_matrix(y_test, rf_predictions_rounded)


print("\nRandom Forest Confusion Matrix:")
print(rf_cm)

rf_accuracy = accuracy_score(y_test, rf_predictions_rounded)

print(f"Random Forest Accuracy: {rf_accuracy}")

Random Forest Mean Squared Error: 0.30123812499999997

Random Forest Confusion Matrix:
[[ 0  0  1  0  0  0]
 [ 0  0  9  1  0  0]
 [ 0  0 99 30  1  0]
 [ 0  0 34 87 11  0]
 [ 0  0  0 25 17  0]
 [ 0  0  0  2  3  0]]
Random Forest Accuracy: 0.634375
